name: Test CI

on:
  push:
    branches:
      - main
    paths:
      - projects/**
  pull_request:
    branches:
      - main
    paths:
      - projects/**

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
          cache: pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Install packages
        run: pnpm install
      - parallel:
          - name: Build
            run: pnpm run build:prod
          - name: Lint
            run: pnpm run lint
